spring:
  application:
    name: hellospringcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hzm121/spring-cloud-config-qianfeng.git
          search-paths: respo
          username: hzm121
          password: Ahzm517lyw
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
