spring:
  application:
    name: hellospringcloud-zipkin
  boot:
    admin:
      client:
        api-path: http://localhost:8084
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
