spring:
  application:
    name: hellospringcloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8762


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
