spring:
  application:
    name: hellospringcloud-zuul
  boot:
    admin:
      client:
        api-path: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hellospringcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hellospringcloud-web-service-admin-feign
