spring:
  application:
    name: hellospringcloud-service-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/